---
abstract: 'Include cpanfile'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.90
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.59
dynamic_config: 0
generated_by: 'Module::Install version 1.06, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-CPANfile
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Module::Install::CPANfile:
    file: lib/Module/Install/CPANfile.pm
    version: 0.11
requires:
  Module::CPANfile: 0.9008
  Module::Install: 0
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Module-Install-CPANfile.git
version: 0.11
x_module_name: Module::Install::CPANfile
