---
abstract: 'Include cpanfile'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Install::CPANfile
name: Module-Install-CPANfile
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Module::Install::CPANfile:
    file: lib/Module/Install/CPANfile.pm
    version: 0.03
requires:
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Module-Install-CPANfile.git
version: 0.03
